### ISSUE TITLE
Use new EMAM parser

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#1]
Yannick (@yannick-deuster) fixed parser so that FAS models can be parsed correctly, now.

Before using new one, please ask if Yannick is completely done now.

So that our example works now.
<img width="686" alt="bildschirmfoto 2017-11-04 um 13 15 06" src="https://user-images.githubusercontent.com/30497492/32405272-a5d99dee-c162-11e7-8403-e029f3c505b3.png">

PS: It is now much faster.

**Comment by 0xJMR** [comment]
The used version of the parser is from the 01. November 2017, hence it is the newest version that has been released to this date. I am waiting till Yannick's changes have been merged into the master branch of the respective language repository.

**Comment by 0xJMR** [comment]
Closing this issue as the necessary modifications have been revoked from the grammar. Feel free to reopen it once new changes to the parser appear.

**Comment by vonwenckstern** [comment]
Ok, i replaced `N(` with `Z(` in the FAS.zip so that the first file has no parsing error
