### ISSUE TITLE
Source code for typescript

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#12]
This repo contains only the minified version of javascript (e.g. browser-detect.min.js).
Where is the actual (readable) source code for this functions?

**Comment by 0xJMR** [comment]
The minified or production source codes have not been written by me, but have been downloaded from various repositories.
One a side note, this repository does not contain any Typescript files, as none of the functionality has been implemented in Typescript. I thought we already talked about this?

**Comment by 0xJMR** [comment]
Do you need something else here or can I close this ticket?

**Comment by 0xJMR** [comment]
You were here in this neck of the woods to open a new issue and to comment on another one. So, I assume the answer is "Yes". I will close this ticket for now.
