### ISSUE TITLE
Extend JavaScript API

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#14]
Please extend the #8 JavaScript API about the following functions:
1. add a JavaScript function `open(filename)` to open a corresponding file (e.g. from an embedded iframe)
2. add a REST URL to open files in the editor and to set the cursor on one of the files at a given line like `ide.embeddedmontiarc.com/ide.htm?mountPlace=xyz&files=[file1, file2, file3]&cursor=file1@13` whereby `file1@13` means that the file1 at line 13 has the position.

The point 1. is used for the generated svg it should replace the following `<rect onclick="window.open('bumperbot.bumperBot.sensors.html','_parent',false)"/>` with a `<rect onclick="openSubComponent('bumperbot.bumperBot.sensors.html')"/>` and `openSubComponent(file)` calls `window.open(file,'_parent',false)` to draw the new subcomponent and `open(file)` to open the new subcomponent.
>> Maybe you can change only the `bumperbot.bumperBot.svg` in the demos repo to show Manual how he should adapt the freemarker template.

The point 2. is used later for tutorials.

Adapt the documentation for both extensions. Thank you.

**Comment by vonwenckstern** [comment]
Opening the file already works very nice.
You probably also implemented 1. (why 2. probably redirects to 1.).

Can you please tell me how to use the JavaScript function 1. (then I would modify the svg files in bumperbot.zip) so that also a new tab is opened. So that Manuel can adopt the SVG code generator.

**Comment by 0xJMR** [comment]
> You probably also implemented 1. (why 2. probably redirects to 1.).

This assumption is false. I will implement this function once I have implemented an API which is less important for you now, but more important for me in the long run.
