### ISSUE TITLE
Disable not needed plugins

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#6]
To improve start-up time (esp. when used the first time), all not needed plugins
should be disabled (so that they will not be delivered and instantiated).
We do not need language support for others than EMA, EMAM (so Python, Go, Java, JavaScript, ...
can be removed).
Since we have no Debugging yet, this can also be removed.
If you find other not useable features for our languages, you can remove them too.

<img width="552" alt="bildschirmfoto 2017-11-13 um 23 00 18" src="https://user-images.githubusercontent.com/30497492/32751657-f7589268-c8c6-11e7-8703-bb4b0017d64a.png">

**Comment by 0xJMR** [comment]
The problem here is that a lot of the plugins are intertwined which means that disabling one might render the loading of another one impossible. I will have a look into this, but this might become rather time-consuming.

**Comment by vonwenckstern** [comment]
Don't spend to much time.
Just remove the obviously ones like go, python language.

Zitat von 0xJMR <notifications@github.com>:

**Comment by vonwenckstern** [comment]
nice: disabling some plugins shortened the startup time for Cloud9-IDE at my Mac from 18sec down to 12sec

**Comment by 0xJMR** [comment]
Are there any more potentially interesting plugins to disable? Otherwise, I will close this issue.
