### ISSUE TITLE
Replace Logo in Editor with Cloud9 plus SE Logo

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#7]
replace this logo
<img width="322" alt="bildschirmfoto 2017-11-13 um 23 07 33" src="https://user-images.githubusercontent.com/30497492/32751885-8969a21e-c8c7-11e7-8b35-1a153f713d60.png">
with the one used here
<img width="336" alt="bildschirmfoto 2017-11-13 um 23 07 49" src="https://user-images.githubusercontent.com/30497492/32751888-8b8d12ec-c8c7-11e7-9c83-7fefe83247fb.png">

**Comment by vonwenckstern** [comment]
you can leave the c9 logo as it is, just add the SE logo (maybe you add only the two letters SE and crop the rest of)

**Comment by 0xJMR** [comment]
It's good that you made the proposal of cropping the logo since I already tried to achieve this with the entire logo and it was messy to say the least. I will have a look into this.

**Comment by vonwenckstern** [comment]
Logo is nice.
Please open (as similar to clicking at the cloud9 icon) a new tab `target=_blank`. We do not want to exit the online IDE.
If it is done, you can close the issue.

**Comment by 0xJMR** [comment]
Closing issue as requested.
