### ISSUE TITLE
Text to Outline synchronization does not work always correctly

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#9]
For ports and instances the text to outline synchonization does not work (when I am at a line with a port or an instance, it marks the connectors outline, but not the corresponding port or subcomponent outline item). For connectors it works. It worked correctly in a previously version.

![image](https://user-images.githubusercontent.com/30497492/32948071-49270a0a-cb9e-11e7-9943-2dd4d5f6a905.png)
![image](https://user-images.githubusercontent.com/30497492/32948108-6b4d2ec0-cb9e-11e7-8fa0-78f673afb00c.png)

**Comment by 0xJMR** [comment]
Interesting, I will look into this on occasion.

**Comment by 0xJMR** [comment]
I think this issue should be resolved. I am closing it for now.
